language: cpp
compiler: clang
sudo: required

os:
- osx
- linux

env:
- LLVM_VERSION=3.9
- LLVM_VERSION=4.0
- LLVM_VERSION=5.0
- LLVM_VERSION=6.0

before_install:
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then make travis.install.macos; fi
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then make travis.install.ubuntu; fi

# Uncomment this line when support Rust
# - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then curl -sf https://static.rust-lang.org/rustup.sh | sudo sh; fi

# Build steps
script:
- if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then make ninja.init travis.test PRECOMPILED_LLVM_DIR=/opt/llvm-$LLVM_VERSION INSTALL_DIR=/tmp/mull; fi
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then make ninja.init travis.test PRECOMPILED_LLVM_DIR=/opt/llvm-$LLVM_VERSION INSTALL_DIR=/tmp/mull; fi

