- name: Setup FreeBSD Machine
  hosts: "{{ host | default('all') }}"

  vars:
    llvm_version: 8.0.0
    platform: freebsd

    package_extensions:
      - sh

    mull_cxx_flags:

    packages:
      - vim
      - cmake
      - ninja
      - git
      - gtar
      - pkgconf
      - sqlite3
      - gmake

  vars_files:
    - helpers/variables.yaml

  tasks:
    - name: Prepare Working Directory
      include: helpers/working-directory.yaml

    - name: Install Required Packages
      pkgng:
        name: "{{ packages }}"
        state: present
      become: true

    - name: Install LLVM
      include: helpers/download-llvm.yaml

    - name: Build Mull
      include: helpers/build-mull.yaml

    - name: Integration Tests
      include: helpers/integration-tests.yaml

